---
- name: execute powershell scripts
  hosts: localhost
  vars:
    triggerapp: "AAP"
    #remote_dir_path: "C:\Users\Administrator\Desktop\ansible"

  tasks:
    - name: create remote directory
      ansible.windows.win_file:
        #path: "{{ remote_dir_path }}"
        path: C:\Users\Administrator\Desktop\ansible
        state: directory

    - name: copy the powershell script
      ansible.windows.win_copy:
        src: my_custome_powershell.ps1
        dest: C:\Users\Administrator\Desktop\ansible 

    - name: execute the powershell script
      ansible.windows.win_shell: C:\Users\Administrator\Desktop\ansible\my_custome_powershell.ps1 "{{ triggerapp }}"
      delegate_to: 54.242.33.178
      register: outps

    - name: print out from powershell script
      debug:
       msg: "{{ outps.stdout_lines }}"
