---
- name: Parse the payload and get the server name
  hosts: all
  tasks:
    - name: print server name
      debug:
        msg: "Running on {{ dynamic_limit }}"
      when: ansible_hostname == dynamic_limit
